### ISSUE TITLE
Regression: Real-time collaboration not working

### ISSUE THREAD

**Issue by Garbash** [Rhizi/rhizi#654]
Inputting, editing or repositioning of a node doesn't update other clients in real-time

**Comment by alon** [comment]
this happens with python2? I didn't see it with it. I specifically tested this this morning. python 3 did have this problem.

**Comment by Garbash** [comment]
Just tested it in cri.rhizi.net. Edited, created and repositioned node and it didn't update the other client.

**Comment by alon** [comment]
after investigation this is an apache mod_proxy_wstunnel issue, recently (April 19, eee8288d78604f7358ca1b9df2612c5684494ba9 in git://git.apache.org/httpd.git - a git readonly clone of apache subversion) it learned to pass a request without the Upgrade header to the next handler, which breaks socket.io 0.9.10 which we use. The trivial solution is to revert this patch or use an older mod_proxy_wstunnel, another would be to investigate fixes to our usage of socket.io or using a newer one (latest is 1.3.4 iirc). Closing because of existence of a workaround.
